# Trigger Mac OS X build (even though this is a Python test)
language: objective-c

before_install:
   # The Travis Homebrew setup comes with python and python@2 pre-installed
   - brew update
   # Hack out readline so that we can test our own version
   - brew remove readline --ignore-dependencies
   - export PATH=/usr/local/bin:$PATH

install:
  - python2 setup.py install
  - python3 setup.py install

before_script:
  - pip2 install pytest
  - pip3 install pytest

script:
  - python2 /usr/local/bin/py.test test.py
  - python3 /usr/local/bin/py.test test.py
