# Trigger Mac OS X build (even though this is a Python test)
language: objective-c

before_install:
   - brew update
   - brew remove python --ignore-dependencies
   - brew remove python@2 --ignore-dependencies
   - brew remove readline --ignore-dependencies
   - brew install python --ignore-dependencies --build-from-source
   - brew install python@2 --ignore-dependencies --build-from-source
   - export PATH=/usr/local/bin:$PATH

install:
  - python2 setup.py install
  - python3 setup.py install

before_script:
  - pip2 install pytest
  - pip3 install pytest

script:
  - python2 /usr/local/bin/py.test test.py
  - python3 /usr/local/bin/py.test test.py
